version: '3'

services:
  mysql:
    image: mysql:8.0
    platform: linux/arm64/v8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "angelina"
      MYSQL_DATABASE: "bluebell_pre"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bluebell-net

  redis:
    image: redis:7.0
    platform: linux/arm64/v8
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass angelina
    volumes:
      - redis_data:/data
    networks:
      - bluebell-net

  etcd:
    image: bitnami/etcd:latest
    platform: linux/arm64/v8
    container_name: etcd-container
    ports:
      - "2379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-container:2379
    volumes:
      - etcd_data:/bitnami/etcd
    networks:
      - bluebell-net

  zookeeper:
    image: zookeeper:latest
    platform: linux/arm64/v8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - bluebell-net

  kafka:
    image: confluentinc/cp-kafka:latest
    platform: linux/arm64/v8
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - bluebell-net

volumes:
  mysql_data:
  redis_data:
  etcd_data:

networks:
  bluebell-net:
    external: true 