# configs/config.yaml
server:
  port: :8080
  version: 1.0
  jwtSecret: bluebell_pre

mysql:
  host: mysql
  port: 3306
  database: bluebell_pre
  username: root
  password: angelina
  charset: utf8mb4
  maxOpenConns: 200
  maxIdleConns: 50

redis:
  host: redis
  port: 6379
  password: "angelina"  
  db: 0
  pool_size: 100
  min_idle_conns: 10

etcd:
  address: etcd:2379

kafka:
  brokers:
    - kafka:9092
  topic: post-votes
  batch_size: 100
  vote_counts_file: data/vote_count.json
